### ISSUE TITLE
Epic: Configurer le projet

### ISSUE THREAD

**Issue by Carolinedanslesnuages** [Carolinedanslesnuages/no-code-vue-dsfr#1]
## Description

Configurer le monorepo, l'environnement de développement, la base de données et les scripts de build et de développement.

## Tâches Associées

- [ ] #1 Installer et configurer le monorepo
- [ ] #2 Configurer l’environnement de développement
- [ ] #3 Configurer la base de données
- [ ] #4 Configurer les scripts de build et de développement
